sudo: required
dist: trusty
group: edge
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
  hosts:
      - magento2.travis
language: php
matrix:
  include:
    - php: 7.3
      env:
       - MAGENTO_VERSION=2.4-develop
       - TEST_SUITE=integration
    - php: 7.3
      env:
       - MAGENTO_VERSION=2.4-develop
       - TEST_SUITE=unit
       - TEST_COVERAGE=true
    - php: 7.3
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=integration
    - php: 7.3
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=unit
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.4-develop
       - TEST_SUITE=integration
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.4-develop
       - TEST_SUITE=unit
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=integration
    - php: 7.2
      env:
       - MAGENTO_VERSION=2.3
       - TEST_SUITE=unit
    - php: 7.2
      env:
        - MAGENTO_VERSION=2.2
        - TEST_SUITE=integration
    - php: 7.2
      env:
        - MAGENTO_VERSION=2.2
        - TEST_SUITE=unit
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2
        - TEST_SUITE=integration
    - php: 7.1
      env:
        - MAGENTO_VERSION=2.2
        - TEST_SUITE=unit
env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - COMPOSER_PACKAGE_NAME=ethanyehuda/magento2-cronjobmanager
cache:
  apt: true
  directories:
    - $HOME/.composer/cache
before_script: ./.travis/before_script.sh
script: phpunit -c magento2/dev/tests/$TEST_SUITE
after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry php magento2/vendor/php-coveralls/php-coveralls/bin/php-coveralls -v ; fi
